# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Melosty

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Melosty

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Melosty/CMakeFiles /root/Melosty//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Melosty/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Melosty

# Build rule for target.
Melosty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Melosty
.PHONY : Melosty

# fast build rule for target.
Melosty/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/build
.PHONY : Melosty/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f include/glfw/CMakeFiles/uninstall.dir/build.make include/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f include/glfw/src/CMakeFiles/glfw.dir/build.make include/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f include/glfw/src/CMakeFiles/update_mappings.dir/build.make include/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

Melosty.o: Melosty.cpp.o
.PHONY : Melosty.o

# target to build an object file
Melosty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/Melosty.cpp.o
.PHONY : Melosty.cpp.o

Melosty.i: Melosty.cpp.i
.PHONY : Melosty.i

# target to preprocess a source file
Melosty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/Melosty.cpp.i
.PHONY : Melosty.cpp.i

Melosty.s: Melosty.cpp.s
.PHONY : Melosty.s

# target to generate assembly for a file
Melosty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/Melosty.cpp.s
.PHONY : Melosty.cpp.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/glad.c.s
.PHONY : glad.c.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_impl_glfw.o: include/imgui/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/imgui_impl_glfw.o

# target to build an object file
include/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/imgui_impl_glfw.cpp.o

include/imgui/imgui_impl_glfw.i: include/imgui/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/imgui_impl_glfw.i

# target to preprocess a source file
include/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/imgui_impl_glfw.cpp.i

include/imgui/imgui_impl_glfw.s: include/imgui/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
include/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/imgui_impl_glfw.cpp.s

include/imgui/imgui_impl_opengl3.o: include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/imgui_impl_opengl3.o

# target to build an object file
include/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/imgui_impl_opengl3.cpp.o

include/imgui/imgui_impl_opengl3.i: include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.cpp.i

include/imgui/imgui_impl_opengl3.s: include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Melosty.dir/build.make CMakeFiles/Melosty.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... Melosty"
	@echo "... glfw"
	@echo "... Melosty.o"
	@echo "... Melosty.i"
	@echo "... Melosty.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_impl_glfw.o"
	@echo "... include/imgui/imgui_impl_glfw.i"
	@echo "... include/imgui/imgui_impl_glfw.s"
	@echo "... include/imgui/imgui_impl_opengl3.o"
	@echo "... include/imgui/imgui_impl_opengl3.i"
	@echo "... include/imgui/imgui_impl_opengl3.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

